# Generated by Django 5.2.18 on 2026-10-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0004_catalog_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='OntologyRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True)),
                ('filename', models.CharField(max_length=200)),
                ('ttl', models.TextField()),
                ('sha256', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
    ]
