# Generated by Django 5.2.18 on 2026-10-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0005_ontology_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontologyrelease',
            name='mapping_template',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ontologyrelease',
            name='template_filename',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ontologyrelease',
            name='template_sha256',
            field=models.CharField(default='', max_length=64),
        ),
    ]
